//
//  FavoritesEntity.swift
//  StoriAppTest
//
//  Created by Alejandro Isai Acosta Martinez on 04/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Entities are simply our models that the interactor uses through 
//  our repository either for the network layer or data persistence.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

enum Favorites {
	// MARK: - Use cases

	enum SomeUseCase {
		struct Request: Codable {}

		struct Response: Codable {}

		struct ViewModel: Codable {}
	}
}