//
//  HomeEntity.swift
//  StoriAppTest
//
//  Created by Alejandro Isai Acosta Martinez on 04/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Entities are simply our models that the interactor uses through 
//  our repository either for the network layer or data persistence.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

enum Home {
	// MARK: - Use cases

	enum TopRatedMoviesUseCase {
		struct Request: Codable {}

        // MARK: - Response
        struct Response: Codable {
            let page: Int
            let results: [Result]
            let totalPages, totalResults: Int

            enum CodingKeys: String, CodingKey {
                case page, results
                case totalPages = "total_pages"
                case totalResults = "total_results"
            }
        }

        // MARK: - Result
        struct Result: Codable {
            let adult: Bool
            let backdropPath: String
            let genreIDS: [Int]
            let id: Int
            let originalLanguage, originalTitle, overview: String
            let popularity: Double
            let posterPath, releaseDate, title: String
            let video: Bool
            let voteAverage: Double
            let voteCount: Int
            var isFavorite: Bool?

            enum CodingKeys: String, CodingKey {
                case adult
                case backdropPath = "backdrop_path"
                case genreIDS = "genre_ids"
                case id
                case originalLanguage = "original_language"
                case originalTitle = "original_title"
                case overview, popularity
                case posterPath = "poster_path"
                case releaseDate = "release_date"
                case title, video
                case voteAverage = "vote_average"
                case voteCount = "vote_count"
            }
        }
	}
}
