//
//  HomePresenter.swift
//  StoriAppTest
//
//  Created by Alejandro Isai Acosta Martinez on 04/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  The presenter is the only layer that communicates with the view 
//  (The rest of layers communicates with the presenter). Basically, 
//  it’s the layer responsible for making decisions based on the 
//  user’s actions sent by The View.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

protocol HomePresentationLogic {
    func presentMoviesResponse(response: Home.TopRatedMoviesUseCase.Response)
    func presentFailure(message: String)
}

class HomePresenter: Presenter, HomePresentationLogic {
    // MARK: - Properties

    lazy var view: HomeDisplayLogic = {
        return self._view as! HomeDisplayLogic
    }()

    // MARK: - PresentationLogic implementation
    
    func presentMoviesResponse(response: Home.TopRatedMoviesUseCase.Response) {
        self.view.displayMovies(moviesResponse: response)
    }

    func presentFailure(message: String) {
        self.view.displayFailure(message: message)
    }
}

