//
//  MovieDetailPresenter.swift
//  StoriAppTest
//
//  Created by Alejandro Isai Acosta Martinez on 05/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  The presenter is the only layer that communicates with the view 
//  (The rest of layers communicates with the presenter). Basically, 
//  it’s the layer responsible for making decisions based on the 
//  user’s actions sent by The View.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

protocol MovieDetailPresentationLogic {
    func presentSuccess(response: MovieDetail.SomeUseCase.Response)
    func presentFailure(message: String)
}

class MovieDetailPresenter: Presenter, MovieDetailPresentationLogic {
    // MARK: - Properties

    lazy var view: MovieDetailDisplayLogic = {
        return self._view as! MovieDetailDisplayLogic
    }()

    // MARK: - PresentationLogic implementation

   func presentSuccess(response: MovieDetail.SomeUseCase.Response) {
        self.view.displaySomething(viewModel: MovieDetail.SomeUseCase.ViewModel())
    }

    func presentFailure(message: String) {
        self.view.displayFailure(message: message)
    }
}

