//
//  MovieDetailRouter.swift
//  StoriAppTest
//
//  Created by Alejandro Isai Acosta Martinez on 05/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This layer is responsible for handling navigation logic: Pushing, 
//  Popping, Presenting UIViewControllers.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import UIKit

protocol MovieDetailRoutingLogic {
	func routeToSomewhere()
}

class MovieDetailRouter: Router, MovieDetailRoutingLogic {
	lazy var view: MovieDetailViewController = {
		return self._view as! MovieDetailViewController
	}()

	func routeToSomewhere() {
		
	}
}
